### PR TITLE
Update actions in README

### PR DESCRIPTION
**Pull request by wrt54g**
I updated the actions/checkout from v2 to v3 in the example config section in the README file.

### CODE REVIEW

**Review by rockoMMB — APPROVED** [review]

**Review by rockoMMB — COMMENTED** [review]
[https://github.com/actions/upload-artifact/pull/332#issue-1288133276]()

**Comment by wrt54g** [comment]
> https://github.com/actions/upload-artifact/pull/332#issue-1288133276

@rockoMMB Link does not work.

**Comment by Smokey365** [comment]
My B rocmmb@icloud.con

**Comment by israelromero19** [comment]
bootgrubgrub.cfg

**Review by israelromero19 — APPROVED** [review]

**Review by israelromero19 — APPROVED** [review]

**Pull request closed without merging**
