### PR TITLE
Bump @actions/artifact to version 0.6.1

### PR DESCRIPTION
**Pull request by konradpabjan**
Bump `@actions/artifact` to version 0.6.1 https://www.npmjs.com/package/@actions/artifact/v/0.6.1 which has a fix for https://github.com/actions/upload-artifact/issues/281

### CODE REVIEW

**Comment by nschonni** [comment]
Not sure if you want to run `npm i` to do https://github.com/actions/upload-artifact/pull/275 here instead

**Comment by konradpabjan** [comment]
@nschonni for the time being we're sticking with `lockfileVersion` of `1`. There hasn't really been an initiative or major reason for us to move up to v2 (yet). In all our other first party actions like `setup-node` and `setup-python` we're still on v1. When we update one we'll probably update all of them.

Also a minor reason why we don't want to immediately move to `v2` is because actions runners ship with `node12` and that is what actions are executed with: https://github.com/actions/upload-artifact/blob/da838ae9595ac94171fa2d4de5a2f117b3e7ac32/action.yml#L27

Node12 ships with `v6` of NPM (npm `6.14.15` according to https://nodejs.org/en/blog/release/v12.22.6/) which uses lockfileVersion 1 so it would be a bit weird to use v2 now (even though it would probably work). And we're not moving to a newer version of node largely for compatibility.

**Comment by nschonni** [comment]
OK, I won't clutter up the discussion here, but the problem is that now that Node 16 is LTS  and ships with NPM 8, anytime you touch the package.json file NPM 8 will upgrade to v2. It makes working with these packages annoying, because you either have to globally install NPM 6 temporarily or keep undoing the upgrades repeatedly.

**Review by yacaovsnc — APPROVED** [review]

**Comment by konradpabjan** [comment]
> OK, I won't clutter up the discussion here, but the problem is that now that Node 16 is LTS and ships with NPM 8, anytime you touch the package.json file NPM 8 will upgrade to v2. It makes working with these packages annoying, because you either have to globally install NPM 6 temporarily or keep undoing the upgrades repeatedly.

Yeah it's a bit annoying 😕 I'll ask around internally if we would want to go ahead and upgrade the lock files for all first party actions. Though just because we're using older versions of node my hunch is we won't want to

**Comment by nschonni** [comment]
I closed that other PR for now, but Node 12 is EOL in 5 months, so it might be good to look at the upgrade sooner than later https://github.com/nodejs/Release

**Pull request merged**
